apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-front
  namespace: scheduler-demo
  labels:
    app: kubernetes-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-front
  template:
    metadata:
      labels:
        app: kubernetes-front
    spec:
      nodeSelector:
        kubernetes-front-node: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: web
          image: kubernetes-front:real-k8s-proxyfix-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-front
  namespace: scheduler-demo
  labels:
    app: kubernetes-front
spec:
  selector:
    app: kubernetes-front
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
